# coding: utf-8

"""
    aind-labtracks-service

     ## aind-labtracks-service  Service to fetch data from LabTracks.  

    The version of the OpenAPI document: 0.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_labtracks_service_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_subject(self) -> None:
        """Test case for get_subject

        Get Subject
        """
        pass

    def test_get_subject_by_protocol_number(self) -> None:
        """Test case for get_subject_by_protocol_number

        Get Subject By Protocol Number
        """
        pass

    def test_get_tasks(self) -> None:
        """Test case for get_tasks

        Get Tasks
        """
        pass


if __name__ == '__main__':
    unittest.main()
